
  CREATE TABLE "COURIERS" 
   (	"COURIER_ID" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"PHONE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(100), 
	"VEHICLE_TYPE" VARCHAR2(50), 
	 PRIMARY KEY ("COURIER_ID")
  USING INDEX  ENABLE
   ) ;