
  CREATE TABLE "CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(50), 
	"LAST_NAME" VARCHAR2(50), 
	"PHONE" VARCHAR2(20), 
	"EMAIL" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(200), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "COUNT_ROWS_TRIGGER" 
BEFORE INSERT ON customers
FOR EACH ROW
DECLARE
  row_count NUMBER;
BEGIN
  row_count := get_table_count('customers') + 1;
  DBMS_OUTPUT.PUT_LINE('Current row count: ' || row_count);
END;
/
ALTER TRIGGER "COUNT_ROWS_TRIGGER" ENABLE;