
  CREATE TABLE "DELIVERIES" 
   (	"ID" NUMBER(10,0), 
	"ORDER_ID" NUMBER(10,0), 
	"COURIER_ID" NUMBER(10,0), 
	"DELIVERY_DATE" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "DELIVERIES" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ORDERS" ("ID") ENABLE;
  ALTER TABLE "DELIVERIES" ADD FOREIGN KEY ("COURIER_ID")
	  REFERENCES "COURIERS" ("COURIER_ID") ENABLE;