
  CREATE TABLE "ORDERS" 
   (	"ID" NUMBER(10,0), 
	"CUSTOMER_ID" NUMBER(10,0), 
	"RESTAURANT_ID" NUMBER(10,0), 
	"COURIER_ID" NUMBER(10,0), 
	"ORDER_DATE" TIMESTAMP (6), 
	"DELIVERY_DATE" TIMESTAMP (6), 
	"STATUS_ID" NUMBER(10,0), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("RESTAURANT_ID")
	  REFERENCES "RESTAURANTS" ("RESTAURANT_ID") ENABLE;
  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("COURIER_ID")
	  REFERENCES "COURIERS" ("COURIER_ID") ENABLE;
  ALTER TABLE "ORDERS" ADD FOREIGN KEY ("STATUS_ID")
	  REFERENCES "ORDER_STATUSES" ("STATUS_ID") ENABLE;