
  CREATE TABLE "RESTAURANTS" 
   (	"RESTAURANT_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(200), 
	"PHONE_NUMBER" VARCHAR2(20), 
	"EMAIL" VARCHAR2(100), 
	 PRIMARY KEY ("RESTAURANT_ID")
  USING INDEX  ENABLE
   ) ;